// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.33.4

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Protocol_2eproto;
}  // extern "C"
namespace Protocol {
class C_LOGIN;
struct C_LOGINDefaultTypeInternal;
extern C_LOGINDefaultTypeInternal _C_LOGIN_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_LOGIN_class_data_;
class C_REGISTER;
struct C_REGISTERDefaultTypeInternal;
extern C_REGISTERDefaultTypeInternal _C_REGISTER_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_REGISTER_class_data_;
class C_TEST;
struct C_TESTDefaultTypeInternal;
extern C_TESTDefaultTypeInternal _C_TEST_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_TEST_class_data_;
class S_LOGIN;
struct S_LOGINDefaultTypeInternal;
extern S_LOGINDefaultTypeInternal _S_LOGIN_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_LOGIN_class_data_;
class S_REGISTER;
struct S_REGISTERDefaultTypeInternal;
extern S_REGISTERDefaultTypeInternal _S_REGISTER_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_REGISTER_class_data_;
class S_TEST;
struct S_TESTDefaultTypeInternal;
extern S_TESTDefaultTypeInternal _S_TEST_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_TEST_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class S_TEST final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_TEST) */ {
 public:
  inline S_TEST() : S_TEST(nullptr) {}
  ~S_TEST() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_TEST* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_TEST));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_TEST(::google::protobuf::internal::ConstantInitialized);

  inline S_TEST(const S_TEST& from) : S_TEST(nullptr, from) {}
  inline S_TEST(S_TEST&& from) noexcept
      : S_TEST(nullptr, ::std::move(from)) {}
  inline S_TEST& operator=(const S_TEST& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_TEST& operator=(S_TEST&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_TEST& default_instance() {
    return *reinterpret_cast<const S_TEST*>(
        &_S_TEST_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(S_TEST& a, S_TEST& b) { a.Swap(&b); }
  inline void Swap(S_TEST* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_TEST* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_TEST* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_TEST>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_TEST& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_TEST& from) { S_TEST::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_TEST* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_TEST"; }

  explicit S_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_TEST& from);
  S_TEST(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_TEST&& from) noexcept
      : S_TEST(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestNumFieldNumber = 2,
    kIsTestFieldNumber = 1,
    kIsLoginFieldNumber = 3,
  };
  // uint64 testNum = 2;
  void clear_testnum() ;
  ::uint64_t testnum() const;
  void set_testnum(::uint64_t value);

  private:
  ::uint64_t _internal_testnum() const;
  void _internal_set_testnum(::uint64_t value);

  public:
  // bool isTest = 1;
  void clear_istest() ;
  bool istest() const;
  void set_istest(bool value);

  private:
  bool _internal_istest() const;
  void _internal_set_istest(bool value);

  public:
  // bool isLogin = 3;
  void clear_islogin() ;
  bool islogin() const;
  void set_islogin(bool value);

  private:
  bool _internal_islogin() const;
  void _internal_set_islogin(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_TEST)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_TEST& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t testnum_;
    bool istest_;
    bool islogin_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_TEST_class_data_;
// -------------------------------------------------------------------

class S_REGISTER final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_REGISTER) */ {
 public:
  inline S_REGISTER() : S_REGISTER(nullptr) {}
  ~S_REGISTER() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_REGISTER* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_REGISTER));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_REGISTER(::google::protobuf::internal::ConstantInitialized);

  inline S_REGISTER(const S_REGISTER& from) : S_REGISTER(nullptr, from) {}
  inline S_REGISTER(S_REGISTER&& from) noexcept
      : S_REGISTER(nullptr, ::std::move(from)) {}
  inline S_REGISTER& operator=(const S_REGISTER& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_REGISTER& operator=(S_REGISTER&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_REGISTER& default_instance() {
    return *reinterpret_cast<const S_REGISTER*>(
        &_S_REGISTER_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(S_REGISTER& a, S_REGISTER& b) { a.Swap(&b); }
  inline void Swap(S_REGISTER* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_REGISTER* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_REGISTER* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_REGISTER>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_REGISTER& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_REGISTER& from) { S_REGISTER::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_REGISTER* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_REGISTER"; }

  explicit S_REGISTER(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_REGISTER(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_REGISTER& from);
  S_REGISTER(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_REGISTER&& from) noexcept
      : S_REGISTER(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 2,
    kPssdFieldNumber = 3,
    kIsSuccessFieldNumber = 1,
  };
  // string id = 2;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string pssd = 3;
  void clear_pssd() ;
  const ::std::string& pssd() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pssd(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pssd();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pssd();
  void set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pssd() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pssd(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pssd();

  public:
  // bool isSuccess = 1;
  void clear_issuccess() ;
  bool issuccess() const;
  void set_issuccess(bool value);

  private:
  bool _internal_issuccess() const;
  void _internal_set_issuccess(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_REGISTER)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_REGISTER& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr pssd_;
    bool issuccess_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_REGISTER_class_data_;
// -------------------------------------------------------------------

class S_LOGIN final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_LOGIN) */ {
 public:
  inline S_LOGIN() : S_LOGIN(nullptr) {}
  ~S_LOGIN() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_LOGIN* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_LOGIN));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_LOGIN(::google::protobuf::internal::ConstantInitialized);

  inline S_LOGIN(const S_LOGIN& from) : S_LOGIN(nullptr, from) {}
  inline S_LOGIN(S_LOGIN&& from) noexcept
      : S_LOGIN(nullptr, ::std::move(from)) {}
  inline S_LOGIN& operator=(const S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOGIN& operator=(S_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOGIN& default_instance() {
    return *reinterpret_cast<const S_LOGIN*>(
        &_S_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(S_LOGIN& a, S_LOGIN& b) { a.Swap(&b); }
  inline void Swap(S_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LOGIN* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_LOGIN>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_LOGIN& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_LOGIN& from) { S_LOGIN::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_LOGIN* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_LOGIN"; }

  explicit S_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_LOGIN& from);
  S_LOGIN(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_LOGIN&& from) noexcept
      : S_LOGIN(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 2,
    kPssdFieldNumber = 3,
    kIsSuccessFieldNumber = 1,
  };
  // string id = 2;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string pssd = 3;
  void clear_pssd() ;
  const ::std::string& pssd() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pssd(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pssd();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pssd();
  void set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pssd() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pssd(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pssd();

  public:
  // bool isSuccess = 1;
  void clear_issuccess() ;
  bool issuccess() const;
  void set_issuccess(bool value);

  private:
  bool _internal_issuccess() const;
  void _internal_set_issuccess(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_LOGIN)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_LOGIN& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr pssd_;
    bool issuccess_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_LOGIN_class_data_;
// -------------------------------------------------------------------

class C_TEST final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_TEST) */ {
 public:
  inline C_TEST() : C_TEST(nullptr) {}
  ~C_TEST() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_TEST* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_TEST));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_TEST(::google::protobuf::internal::ConstantInitialized);

  inline C_TEST(const C_TEST& from) : C_TEST(nullptr, from) {}
  inline C_TEST(C_TEST&& from) noexcept
      : C_TEST(nullptr, ::std::move(from)) {}
  inline C_TEST& operator=(const C_TEST& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_TEST& operator=(C_TEST&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_TEST& default_instance() {
    return *reinterpret_cast<const C_TEST*>(
        &_C_TEST_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(C_TEST& a, C_TEST& b) { a.Swap(&b); }
  inline void Swap(C_TEST* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_TEST* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_TEST* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_TEST>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_TEST& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_TEST& from) { C_TEST::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_TEST* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_TEST"; }

  explicit C_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_TEST& from);
  C_TEST(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_TEST&& from) noexcept
      : C_TEST(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestNumFieldNumber = 2,
    kIsTestFieldNumber = 1,
    kIsLoginFieldNumber = 3,
  };
  // uint64 testNum = 2;
  void clear_testnum() ;
  ::uint64_t testnum() const;
  void set_testnum(::uint64_t value);

  private:
  ::uint64_t _internal_testnum() const;
  void _internal_set_testnum(::uint64_t value);

  public:
  // bool isTest = 1;
  void clear_istest() ;
  bool istest() const;
  void set_istest(bool value);

  private:
  bool _internal_istest() const;
  void _internal_set_istest(bool value);

  public:
  // bool isLogin = 3;
  void clear_islogin() ;
  bool islogin() const;
  void set_islogin(bool value);

  private:
  bool _internal_islogin() const;
  void _internal_set_islogin(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_TEST)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_TEST& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t testnum_;
    bool istest_;
    bool islogin_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_TEST_class_data_;
// -------------------------------------------------------------------

class C_REGISTER final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_REGISTER) */ {
 public:
  inline C_REGISTER() : C_REGISTER(nullptr) {}
  ~C_REGISTER() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_REGISTER* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_REGISTER));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_REGISTER(::google::protobuf::internal::ConstantInitialized);

  inline C_REGISTER(const C_REGISTER& from) : C_REGISTER(nullptr, from) {}
  inline C_REGISTER(C_REGISTER&& from) noexcept
      : C_REGISTER(nullptr, ::std::move(from)) {}
  inline C_REGISTER& operator=(const C_REGISTER& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_REGISTER& operator=(C_REGISTER&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_REGISTER& default_instance() {
    return *reinterpret_cast<const C_REGISTER*>(
        &_C_REGISTER_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(C_REGISTER& a, C_REGISTER& b) { a.Swap(&b); }
  inline void Swap(C_REGISTER* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_REGISTER* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_REGISTER* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_REGISTER>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_REGISTER& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_REGISTER& from) { C_REGISTER::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_REGISTER* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_REGISTER"; }

  explicit C_REGISTER(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_REGISTER(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_REGISTER& from);
  C_REGISTER(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_REGISTER&& from) noexcept
      : C_REGISTER(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kPssdFieldNumber = 2,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string pssd = 2;
  void clear_pssd() ;
  const ::std::string& pssd() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pssd(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pssd();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pssd();
  void set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pssd() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pssd(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pssd();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_REGISTER)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_REGISTER& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr pssd_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_REGISTER_class_data_;
// -------------------------------------------------------------------

class C_LOGIN final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_LOGIN) */ {
 public:
  inline C_LOGIN() : C_LOGIN(nullptr) {}
  ~C_LOGIN() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_LOGIN* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_LOGIN));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_LOGIN(::google::protobuf::internal::ConstantInitialized);

  inline C_LOGIN(const C_LOGIN& from) : C_LOGIN(nullptr, from) {}
  inline C_LOGIN(C_LOGIN&& from) noexcept
      : C_LOGIN(nullptr, ::std::move(from)) {}
  inline C_LOGIN& operator=(const C_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOGIN& operator=(C_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOGIN& default_instance() {
    return *reinterpret_cast<const C_LOGIN*>(
        &_C_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(C_LOGIN& a, C_LOGIN& b) { a.Swap(&b); }
  inline void Swap(C_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LOGIN* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_LOGIN>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_LOGIN& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_LOGIN& from) { C_LOGIN::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_LOGIN* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_LOGIN"; }

  explicit C_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_LOGIN& from);
  C_LOGIN(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_LOGIN&& from) noexcept
      : C_LOGIN(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kPssdFieldNumber = 2,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string pssd = 2;
  void clear_pssd() ;
  const ::std::string& pssd() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pssd(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pssd();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pssd();
  void set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pssd() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pssd(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pssd();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_LOGIN)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_LOGIN& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr pssd_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_LOGIN_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// C_TEST

// bool isTest = 1;
inline void C_TEST::clear_istest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istest_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool C_TEST::istest() const {
  // @@protoc_insertion_point(field_get:Protocol.C_TEST.isTest)
  return _internal_istest();
}
inline void C_TEST::set_istest(bool value) {
  _internal_set_istest(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.C_TEST.isTest)
}
inline bool C_TEST::_internal_istest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.istest_;
}
inline void C_TEST::_internal_set_istest(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istest_ = value;
}

// uint64 testNum = 2;
inline void C_TEST::clear_testnum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testnum_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t C_TEST::testnum() const {
  // @@protoc_insertion_point(field_get:Protocol.C_TEST.testNum)
  return _internal_testnum();
}
inline void C_TEST::set_testnum(::uint64_t value) {
  _internal_set_testnum(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.C_TEST.testNum)
}
inline ::uint64_t C_TEST::_internal_testnum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testnum_;
}
inline void C_TEST::_internal_set_testnum(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testnum_ = value;
}

// bool isLogin = 3;
inline void C_TEST::clear_islogin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.islogin_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool C_TEST::islogin() const {
  // @@protoc_insertion_point(field_get:Protocol.C_TEST.isLogin)
  return _internal_islogin();
}
inline void C_TEST::set_islogin(bool value) {
  _internal_set_islogin(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.C_TEST.isLogin)
}
inline bool C_TEST::_internal_islogin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.islogin_;
}
inline void C_TEST::_internal_set_islogin(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.islogin_ = value;
}

// -------------------------------------------------------------------

// S_TEST

// bool isTest = 1;
inline void S_TEST::clear_istest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istest_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool S_TEST::istest() const {
  // @@protoc_insertion_point(field_get:Protocol.S_TEST.isTest)
  return _internal_istest();
}
inline void S_TEST::set_istest(bool value) {
  _internal_set_istest(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.S_TEST.isTest)
}
inline bool S_TEST::_internal_istest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.istest_;
}
inline void S_TEST::_internal_set_istest(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istest_ = value;
}

// uint64 testNum = 2;
inline void S_TEST::clear_testnum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testnum_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t S_TEST::testnum() const {
  // @@protoc_insertion_point(field_get:Protocol.S_TEST.testNum)
  return _internal_testnum();
}
inline void S_TEST::set_testnum(::uint64_t value) {
  _internal_set_testnum(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.S_TEST.testNum)
}
inline ::uint64_t S_TEST::_internal_testnum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testnum_;
}
inline void S_TEST::_internal_set_testnum(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testnum_ = value;
}

// bool isLogin = 3;
inline void S_TEST::clear_islogin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.islogin_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool S_TEST::islogin() const {
  // @@protoc_insertion_point(field_get:Protocol.S_TEST.isLogin)
  return _internal_islogin();
}
inline void S_TEST::set_islogin(bool value) {
  _internal_set_islogin(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.S_TEST.isLogin)
}
inline bool S_TEST::_internal_islogin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.islogin_;
}
inline void S_TEST::_internal_set_islogin(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.islogin_ = value;
}

// -------------------------------------------------------------------

// C_LOGIN

// string id = 1;
inline void C_LOGIN::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& C_LOGIN::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LOGIN.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_LOGIN::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LOGIN.id)
}
inline ::std::string* PROTOBUF_NONNULL C_LOGIN::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LOGIN.id)
  return _s;
}
inline const ::std::string& C_LOGIN::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void C_LOGIN::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_LOGIN::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_LOGIN::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LOGIN.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void C_LOGIN::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LOGIN.id)
}

// string pssd = 2;
inline void C_LOGIN::clear_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& C_LOGIN::pssd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LOGIN.pssd)
  return _internal_pssd();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_LOGIN::set_pssd(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.pssd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LOGIN.pssd)
}
inline ::std::string* PROTOBUF_NONNULL C_LOGIN::mutable_pssd()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_pssd();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LOGIN.pssd)
  return _s;
}
inline const ::std::string& C_LOGIN::_internal_pssd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pssd_.Get();
}
inline void C_LOGIN::_internal_set_pssd(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_LOGIN::_internal_mutable_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pssd_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_LOGIN::release_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LOGIN.pssd)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.pssd_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pssd_.Set("", GetArena());
  }
  return released;
}
inline void C_LOGIN::set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.pssd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pssd_.IsDefault()) {
    _impl_.pssd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LOGIN.pssd)
}

// -------------------------------------------------------------------

// S_LOGIN

// bool isSuccess = 1;
inline void S_LOGIN::clear_issuccess() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issuccess_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool S_LOGIN::issuccess() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.isSuccess)
  return _internal_issuccess();
}
inline void S_LOGIN::set_issuccess(bool value) {
  _internal_set_issuccess(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.isSuccess)
}
inline bool S_LOGIN::_internal_issuccess() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.issuccess_;
}
inline void S_LOGIN::_internal_set_issuccess(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issuccess_ = value;
}

// string id = 2;
inline void S_LOGIN::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& S_LOGIN::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_LOGIN::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.id)
}
inline ::std::string* PROTOBUF_NONNULL S_LOGIN::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.S_LOGIN.id)
  return _s;
}
inline const ::std::string& S_LOGIN::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void S_LOGIN::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_LOGIN::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_LOGIN::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_LOGIN.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void S_LOGIN::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_LOGIN.id)
}

// string pssd = 3;
inline void S_LOGIN::clear_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& S_LOGIN::pssd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.pssd)
  return _internal_pssd();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_LOGIN::set_pssd(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.pssd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.pssd)
}
inline ::std::string* PROTOBUF_NONNULL S_LOGIN::mutable_pssd()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_pssd();
  // @@protoc_insertion_point(field_mutable:Protocol.S_LOGIN.pssd)
  return _s;
}
inline const ::std::string& S_LOGIN::_internal_pssd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pssd_.Get();
}
inline void S_LOGIN::_internal_set_pssd(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_LOGIN::_internal_mutable_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pssd_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_LOGIN::release_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_LOGIN.pssd)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.pssd_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pssd_.Set("", GetArena());
  }
  return released;
}
inline void S_LOGIN::set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.pssd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pssd_.IsDefault()) {
    _impl_.pssd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_LOGIN.pssd)
}

// -------------------------------------------------------------------

// C_REGISTER

// string id = 1;
inline void C_REGISTER::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& C_REGISTER::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_REGISTER.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_REGISTER::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_REGISTER.id)
}
inline ::std::string* PROTOBUF_NONNULL C_REGISTER::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_REGISTER.id)
  return _s;
}
inline const ::std::string& C_REGISTER::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void C_REGISTER::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_REGISTER::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_REGISTER::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_REGISTER.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void C_REGISTER::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_REGISTER.id)
}

// string pssd = 2;
inline void C_REGISTER::clear_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& C_REGISTER::pssd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_REGISTER.pssd)
  return _internal_pssd();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_REGISTER::set_pssd(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.pssd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_REGISTER.pssd)
}
inline ::std::string* PROTOBUF_NONNULL C_REGISTER::mutable_pssd()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_pssd();
  // @@protoc_insertion_point(field_mutable:Protocol.C_REGISTER.pssd)
  return _s;
}
inline const ::std::string& C_REGISTER::_internal_pssd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pssd_.Get();
}
inline void C_REGISTER::_internal_set_pssd(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_REGISTER::_internal_mutable_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pssd_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_REGISTER::release_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_REGISTER.pssd)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.pssd_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pssd_.Set("", GetArena());
  }
  return released;
}
inline void C_REGISTER::set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.pssd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pssd_.IsDefault()) {
    _impl_.pssd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_REGISTER.pssd)
}

// -------------------------------------------------------------------

// S_REGISTER

// bool isSuccess = 1;
inline void S_REGISTER::clear_issuccess() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issuccess_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool S_REGISTER::issuccess() const {
  // @@protoc_insertion_point(field_get:Protocol.S_REGISTER.isSuccess)
  return _internal_issuccess();
}
inline void S_REGISTER::set_issuccess(bool value) {
  _internal_set_issuccess(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.S_REGISTER.isSuccess)
}
inline bool S_REGISTER::_internal_issuccess() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.issuccess_;
}
inline void S_REGISTER::_internal_set_issuccess(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issuccess_ = value;
}

// string id = 2;
inline void S_REGISTER::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& S_REGISTER::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_REGISTER.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_REGISTER::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_REGISTER.id)
}
inline ::std::string* PROTOBUF_NONNULL S_REGISTER::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.S_REGISTER.id)
  return _s;
}
inline const ::std::string& S_REGISTER::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void S_REGISTER::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_REGISTER::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_REGISTER::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_REGISTER.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void S_REGISTER::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_REGISTER.id)
}

// string pssd = 3;
inline void S_REGISTER::clear_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& S_REGISTER::pssd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_REGISTER.pssd)
  return _internal_pssd();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_REGISTER::set_pssd(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.pssd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_REGISTER.pssd)
}
inline ::std::string* PROTOBUF_NONNULL S_REGISTER::mutable_pssd()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_pssd();
  // @@protoc_insertion_point(field_mutable:Protocol.S_REGISTER.pssd)
  return _s;
}
inline const ::std::string& S_REGISTER::_internal_pssd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pssd_.Get();
}
inline void S_REGISTER::_internal_set_pssd(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pssd_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_REGISTER::_internal_mutable_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pssd_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_REGISTER::release_pssd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_REGISTER.pssd)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.pssd_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pssd_.Set("", GetArena());
  }
  return released;
}
inline void S_REGISTER::set_allocated_pssd(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.pssd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pssd_.IsDefault()) {
    _impl_.pssd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_REGISTER.pssd)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
