// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.33.4

#include "Protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr S_TEST::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        testnum_{::uint64_t{0u}},
        istest_{false},
        islogin_{false} {}

template <typename>
PROTOBUF_CONSTEXPR S_TEST::S_TEST(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(S_TEST_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_TESTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_TESTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_TESTDefaultTypeInternal() {}
  union {
    S_TEST _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_TESTDefaultTypeInternal _S_TEST_default_instance_;

inline constexpr C_TEST::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        testnum_{::uint64_t{0u}},
        istest_{false},
        islogin_{false} {}

template <typename>
PROTOBUF_CONSTEXPR C_TEST::C_TEST(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(C_TEST_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C_TESTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_TESTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_TESTDefaultTypeInternal() {}
  union {
    C_TEST _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_TESTDefaultTypeInternal _C_TEST_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_Protocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::C_TEST, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::C_TEST, _impl_.istest_),
        PROTOBUF_FIELD_OFFSET(::Protocol::C_TEST, _impl_.testnum_),
        PROTOBUF_FIELD_OFFSET(::Protocol::C_TEST, _impl_.islogin_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::S_TEST, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::S_TEST, _impl_.istest_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S_TEST, _impl_.testnum_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S_TEST, _impl_.islogin_),
        1,
        0,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Protocol::C_TEST)},
        {9, sizeof(::Protocol::S_TEST)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Protocol::_C_TEST_default_instance_._instance,
    &::Protocol::_S_TEST_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\":\n\006C_TEST\022\016\n\006"
    "isTest\030\001 \001(\010\022\017\n\007testNum\030\002 \001(\004\022\017\n\007isLogin"
    "\030\003 \001(\010\":\n\006S_TEST\022\016\n\006isTest\030\001 \001(\010\022\017\n\007test"
    "Num\030\002 \001(\004\022\017\n\007isLogin\030\003 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    154,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
namespace Protocol {
// ===================================================================

class C_TEST::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<C_TEST>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C_TEST, _impl_._has_bits_);
};

C_TEST::C_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C_TEST_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.C_TEST)
}
C_TEST::C_TEST(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_TEST& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C_TEST_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE C_TEST::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void C_TEST::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, testnum_),
           0,
           offsetof(Impl_, islogin_) -
               offsetof(Impl_, testnum_) +
               sizeof(Impl_::islogin_));
}
C_TEST::~C_TEST() {
  // @@protoc_insertion_point(destructor:Protocol.C_TEST)
  SharedDtor(*this);
}
inline void C_TEST::SharedDtor(MessageLite& self) {
  C_TEST& this_ = static_cast<C_TEST&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL C_TEST::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) C_TEST(arena);
}
constexpr auto C_TEST::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(C_TEST),
                                            alignof(C_TEST));
}
constexpr auto C_TEST::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_C_TEST_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &C_TEST::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<C_TEST>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &C_TEST::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<C_TEST>(), &C_TEST::ByteSizeLong,
              &C_TEST::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(C_TEST, _impl_._cached_size_),
          false,
      },
      &C_TEST::kDescriptorMethods,
      &descriptor_table_Protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull C_TEST_class_data_ =
        C_TEST::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
C_TEST::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&C_TEST_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(C_TEST_class_data_.tc_table);
  return C_TEST_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
C_TEST::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C_TEST, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    C_TEST_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::C_TEST>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool isTest = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(C_TEST, _impl_.istest_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.istest_)}},
    // uint64 testNum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(C_TEST, _impl_.testnum_), 0>(),
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.testnum_)}},
    // bool isLogin = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(C_TEST, _impl_.islogin_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.islogin_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isTest = 1;
    {PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.istest_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // uint64 testNum = 2;
    {PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.testnum_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool isLogin = 3;
    {PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.islogin_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void C_TEST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C_TEST)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.testnum_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.islogin_) -
        reinterpret_cast<char*>(&_impl_.testnum_)) + sizeof(_impl_.islogin_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL C_TEST::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const C_TEST& this_ = static_cast<const C_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL C_TEST::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const C_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C_TEST)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool isTest = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_istest() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_istest(), target);
    }
  }

  // uint64 testNum = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_testnum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_testnum(), target);
    }
  }

  // bool isLogin = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_islogin() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_islogin(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C_TEST)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t C_TEST::ByteSizeLong(const MessageLite& base) {
  const C_TEST& this_ = static_cast<const C_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t C_TEST::ByteSizeLong() const {
  const C_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.C_TEST)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // uint64 testNum = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_testnum() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_testnum());
      }
    }
    // bool isTest = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_istest() != 0) {
        total_size += 2;
      }
    }
    // bool isLogin = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_islogin() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void C_TEST::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<C_TEST*>(&to_msg);
  auto& from = static_cast<const C_TEST&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C_TEST)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_testnum() != 0) {
        _this->_impl_.testnum_ = from._impl_.testnum_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_istest() != 0) {
        _this->_impl_.istest_ = from._impl_.istest_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_islogin() != 0) {
        _this->_impl_.islogin_ = from._impl_.islogin_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void C_TEST::CopyFrom(const C_TEST& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C_TEST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C_TEST::InternalSwap(C_TEST* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.islogin_)
      + sizeof(C_TEST::_impl_.islogin_)
      - PROTOBUF_FIELD_OFFSET(C_TEST, _impl_.testnum_)>(
          reinterpret_cast<char*>(&_impl_.testnum_),
          reinterpret_cast<char*>(&other->_impl_.testnum_));
}

::google::protobuf::Metadata C_TEST::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_TEST::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<S_TEST>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S_TEST, _impl_._has_bits_);
};

S_TEST::S_TEST(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S_TEST_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_TEST)
}
S_TEST::S_TEST(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_TEST& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S_TEST_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE S_TEST::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void S_TEST::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, testnum_),
           0,
           offsetof(Impl_, islogin_) -
               offsetof(Impl_, testnum_) +
               sizeof(Impl_::islogin_));
}
S_TEST::~S_TEST() {
  // @@protoc_insertion_point(destructor:Protocol.S_TEST)
  SharedDtor(*this);
}
inline void S_TEST::SharedDtor(MessageLite& self) {
  S_TEST& this_ = static_cast<S_TEST&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL S_TEST::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) S_TEST(arena);
}
constexpr auto S_TEST::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_TEST),
                                            alignof(S_TEST));
}
constexpr auto S_TEST::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_S_TEST_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &S_TEST::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<S_TEST>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &S_TEST::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<S_TEST>(), &S_TEST::ByteSizeLong,
              &S_TEST::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(S_TEST, _impl_._cached_size_),
          false,
      },
      &S_TEST::kDescriptorMethods,
      &descriptor_table_Protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull S_TEST_class_data_ =
        S_TEST::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S_TEST::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S_TEST_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(S_TEST_class_data_.tc_table);
  return S_TEST_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
S_TEST::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S_TEST, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    S_TEST_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::S_TEST>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool isTest = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S_TEST, _impl_.istest_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.istest_)}},
    // uint64 testNum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(S_TEST, _impl_.testnum_), 0>(),
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.testnum_)}},
    // bool isLogin = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S_TEST, _impl_.islogin_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.islogin_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isTest = 1;
    {PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.istest_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // uint64 testNum = 2;
    {PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.testnum_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool isLogin = 3;
    {PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.islogin_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void S_TEST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_TEST)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.testnum_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.islogin_) -
        reinterpret_cast<char*>(&_impl_.testnum_)) + sizeof(_impl_.islogin_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL S_TEST::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const S_TEST& this_ = static_cast<const S_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL S_TEST::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const S_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_TEST)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool isTest = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_istest() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_istest(), target);
    }
  }

  // uint64 testNum = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_testnum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_testnum(), target);
    }
  }

  // bool isLogin = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_islogin() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_islogin(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_TEST)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t S_TEST::ByteSizeLong(const MessageLite& base) {
  const S_TEST& this_ = static_cast<const S_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t S_TEST::ByteSizeLong() const {
  const S_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.S_TEST)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // uint64 testNum = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_testnum() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_testnum());
      }
    }
    // bool isTest = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_istest() != 0) {
        total_size += 2;
      }
    }
    // bool isLogin = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_islogin() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void S_TEST::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<S_TEST*>(&to_msg);
  auto& from = static_cast<const S_TEST&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_TEST)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_testnum() != 0) {
        _this->_impl_.testnum_ = from._impl_.testnum_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_istest() != 0) {
        _this->_impl_.istest_ = from._impl_.istest_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_islogin() != 0) {
        _this->_impl_.islogin_ = from._impl_.islogin_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void S_TEST::CopyFrom(const S_TEST& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_TEST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_TEST::InternalSwap(S_TEST* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.islogin_)
      + sizeof(S_TEST::_impl_.islogin_)
      - PROTOBUF_FIELD_OFFSET(S_TEST, _impl_.testnum_)>(
          reinterpret_cast<char*>(&_impl_.testnum_),
          reinterpret_cast<char*>(&other->_impl_.testnum_));
}

::google::protobuf::Metadata S_TEST::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
